[terminal.shell]
args = ['--login']
program = "/run/current-system/sw/bin/zsh"

[cursor]
style = "Beam"

[font]
size = 16.0



[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.5

[window.padding]
x = 6
y = 0

#[window.dimensions]
#columns = 90
#lines = 25


# alacritty.toml

[colors.primary]
background = "#1a2332"
foreground = "#a4b1cd"

[colors.selection]
text = "#ffffff"
background = "#313f55"

[colors.cursor]
text = '#eee9fc'
cursor = '#eee9fc'

[colors.normal]
black = "#000000"
red = "#ff3e3e"
green = "#9fef00"
yellow = "#ffaf00"
blue = "#5cb2ff"
magenta = "#9f00ff"
cyan = "#2ee7b6"
white = "#ffffff"

[colors.bright]
black = "#666666"
red = "#ff8484"
green = "#c5f467"
yellow = "#ffcc5c"
blue = "#5cb2ff"
magenta = "#c16cfa"
cyan = "#5cecc6"
white = "#ffffff"


[terminal]
